# .github/labels.yml

- name: type: feature
  color: 1d76db
  description: New feature or enhancement

- name: type: bug
  color: d73a4a
  description: Something is broken

- name: type: chore
  color: cccccc
  description: Maintenance tasks or non-feature work

- name: type: epic
  color: 5319e7
  description: High-level feature consisting of multiple tasks

- name: priority: high
  color: b60205
  description: Critical priority, must be done soon

- name: priority: medium
  color: fbca04
  description: Normal priority

- name: priority: low
  color: 0e8a16
  description: Low priority, can be deferred

- name: status: backlog
  color: e4e669
  description: Not started yet

- name: status: in progress
  color: 0052cc
  description: Currently being worked on

- name: status: review
  color: 5319e7
  description: Under code review

- name: status: done
  color: 0e8a16
  description: Task completed

- name: status: blocked
  color: d93f0b
  description: Blocked by another issue or dependency
