name: counter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
      sdk: flutter
  flutter_localizations:
      sdk: flutter
  vision:
    path: ../vision
  universal_platform: ^1.1.0
  nested: ^1.0.0
  path: ^1.9.0
  protobuf: ^3.1.0
  provider: ^6.1.2
  carousel_slider: ^4.1.1
  auto_size_text: ^3.0.0
  beamer: ^1.6.1
  reactive_forms: ^17.0.1
  calendar_date_picker2: ^1.1.7
  badges: ^3.1.2
  cupertino_listview: ^2.0.0
  cross_file: ^0.3.4+2
  auto_animated: ^3.2.0
  sliding_up_panel: ^2.0.0+1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  camera: ^0.11.1
  camera_macos: ^0.0.9
  camera_windows: ^0.2.6+2
  uuid: ^4.5.1
  intl: ^0.19.0
  wakelock_plus: ^1.2.10
  sensors_plus: ^6.1.1
  super_cupertino_navigation_bar: ^2.1.2
  package_info_plus: ^8.2.1
  flutter_colorpicker: ^1.1.0
  fl_chart: ^0.70.2
  image_picker: ^1.1.2
  input_quantity: ^2.5.1
  drift: ^2.25.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  sqlite3_flutter_libs: ^0.5.31
  locale_names: ^1.1.1
  timeago: ^3.7.0
  flutter_native_splash: ^2.4.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^5.0.0
  analyzer: ^6.11.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  drift_dev: ^2.25.2

dependency_overrides:
  analyzer: ^7.1.0
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
      # rename assets/ to asset/ ,this can avoid ci mis-replace "assets/" string in main.dart.js
      - assets/icon/
      - assets/images/

flutter_native_splash:
  color: "#181743"
  image: "assets/images/background.jpg"
  ios_content_mode: scaleAspectFill
  android_12:
   image: "assets/images/background.jpg"