name: counter
publish_to: none
environment:
  sdk: '>=3.11.0 <4.0.0'
workspace:
  - apps/counter_app
  - packages/*
dev_dependencies:
  melos: ^7.4.0

melos:
  command:
    bootstrap:
      runPubGetInParallel: true

  # MOVE YOUR SCRIPTS INSIDE HERE
  scripts:
    get:
      run: melos exec -- flutter pub get

    clean:
      run: melos exec -- flutter clean

    build:
      run: melos exec --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"

    watch:
      run: melos exec --depends-on="build_runner" -- "dart run build_runner watch --delete-conflicting-outputs"

    analyze:
      run: melos exec -- flutter analyze

    test:
      run: melos exec -- flutter test