# ios/fastlane/Fastfile

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the Apple App Store(ios)"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"]
    )

    # Path pointing to the project root relative to ios/fastlane/
    build_num_file = "../../.build_number_ios"

    # Read the current tracking number or start at 0 if it doesn't exist
    if File.exist?(build_num_file)
      current_build = File.read(build_num_file).strip.to_i
    else
      current_build = 0
    end

    # Increment the counter
    next_build_number = current_build + 1


    # Inject the build number into your Xcode project configurations
    increment_build_number(
      xcodeproj: "Counter.xcodeproj",
      build_number: next_build_number
    )

    # Fetch and install the iOS profile
    get_provisioning_profile(
      app_identifier: "com.piyuo.counter",
    )

    # Build the app with the newly incremented build number
    build_app(
      workspace: "Counter.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.piyuo.counter" => Actions.lane_context[SharedValues::SIGH_NAME]
        }
      }
    )

    # Upload the app to App Store Connect
    upload_to_app_store(
      submit_for_review: true,
      precheck_include_in_app_purchases: false,
      support_url: {
        'default' => 'https://piyuo.com'
      },
      copyright: "#{Time.now.year} Chien-Chih Liu"
    )

    File.write(build_num_file, next_build_number.to_s)
    UI.message("Shared Global Build Number: #{current_build} ──> Incrementing to: #{next_build_number}")
  end
end