name: feature_pip
description: "Picture in picture UI"
version: 1.5.2
resolution: workspace
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  shared_l10n: any
  flutter:
    sdk: flutter
  flutter_appkit:
    git:
      url: https://github.com/piyuo/flutter-appkit.git
      ref: v3.8.1
  liquid_glass_widgets: ^1.2.3
  flutter_riverpod: ^3.4.2 # block by analyzer
  riverpod_annotation: ^4.0.6 # block by analyzer
  universal_platform: ^1.1.0
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  go_router: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.8.1
  flutter_lints: ^6.0.0
  analyzer: ^13.3.0
  riverpod_generator: ^4.0.8 # block by analyzer
  build_runner: ^2.16.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
