# macos/fastlane/Fastfile

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the Apple App Store(macos)"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"]
    )


    # Get current build number from pubspec.yaml
    flutter_version = get_flutter_version(pubspec_location: "../../pubspec.yaml")
    current_build_number = flutter_version["build_number"]

    # Set the build number from pubspec.yaml
    increment_build_number(
      xcodeproj: "Counter.xcodeproj",
      build_number: current_build_number
    )

    # Build the app with the newly incremented build number
    build_app(workspace: "Counter.xcworkspace", scheme: "Runner",export_method: "app-store")

    # Upload the app to App Store Connect
    upload_to_app_store(
      precheck_include_in_app_purchases: false
    )
  end
end
