# macos/fastlane/Fastfile

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the Apple App Store(macos)"
  lane :release do
    # Fetch the latest build number from App Store Connect
    # This ensures we always increment from the highest number Apple knows about
    current_app_store_build_number = app_store_build_number()

    # Increment the build number based on the fetched value
    # We add 1 to the highest build number found on App Store Connect
    new_build_number = (current_app_store_build_number.to_i + 1).to_s
    increment_build_number(
      xcodeproj: "Counter.xcodeproj",
      build_number: new_build_number
    )

    # Build the app with the newly incremented build number
    build_app(workspace: "Counter.xcworkspace", scheme: "Runner",export_method: "app-store")

    # Upload the app to App Store Connect
    upload_to_app_store
  end
end
