# macos/fastlane/Fastfile

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the Apple App Store(macos)"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"]
    )


    # Get current build number from pubspec.yaml
    pubspec_path = "../../pubspec.yaml"
    pubspec_content = File.read(pubspec_path)
    version_line = pubspec_content.match(/^version:\s*(.+)$/)

    if version_line && version_line[1].include?('+')
      current_build_number = version_line[1].split('+').last.strip
    else
      UI.user_error!("Could not find build number in pubspec.yaml")
    end

    # Set the build number from pubspec.yaml
    increment_build_number(
      xcodeproj: "Counter.xcodeproj",
      build_number: current_build_number
    )

    # Build the app with the newly incremented build number
    build_app(workspace: "Counter.xcworkspace", scheme: "Runner",export_method: "app-store")

    # Upload the app to App Store Connect
    upload_to_app_store(
      precheck_include_in_app_purchases: false
    )
  end
end
