// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjnK_AJijWwqQdpIKJzGJzcJZbvicFJAM',
    appId: '1:339726104003:android:30a83c0a5f86ed18e37976',
    messagingSenderId: '339726104003',
    projectId: 'counter-964dc',
    storageBucket: 'counter-964dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05_2KKCP6tc0Q_E3yHbPklUw1Dlm8dyE',
    appId: '1:339726104003:ios:29bd9a2427a0cbdbe37976',
    messagingSenderId: '339726104003',
    projectId: 'counter-964dc',
    storageBucket: 'counter-964dc.firebasestorage.app',
    iosBundleId: 'com.piyuo.counter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05_2KKCP6tc0Q_E3yHbPklUw1Dlm8dyE',
    appId: '1:339726104003:ios:29bd9a2427a0cbdbe37976',
    messagingSenderId: '339726104003',
    projectId: 'counter-964dc',
    storageBucket: 'counter-964dc.firebasestorage.app',
    iosBundleId: 'com.piyuo.counter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVg0pMo4lJcIttCSZXeNiZc-74Ekudn7Y',
    appId: '1:339726104003:web:c83fe6078e21b8a7e37976',
    messagingSenderId: '339726104003',
    projectId: 'counter-964dc',
    authDomain: 'counter-964dc.firebaseapp.com',
    storageBucket: 'counter-964dc.firebasestorage.app',
    measurementId: 'G-EQE0F62MMG',
  );
}
