// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// We edit this file only return macos/ios/android , and remove web/windows/linux support cause Firebase won't support them.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return macos;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return macos;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjnK_AJijWwqQdpIKJzGJzcJZbvicFJAM',
    appId: '1:339726104003:android:30a83c0a5f86ed18e37976',
    messagingSenderId: '339726104003',
    projectId: 'counter-964dc',
    storageBucket: 'counter-964dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05_2KKCP6tc0Q_E3yHbPklUw1Dlm8dyE',
    appId: '1:339726104003:ios:29bd9a2427a0cbdbe37976',
    messagingSenderId: '339726104003',
    projectId: 'counter-964dc',
    storageBucket: 'counter-964dc.firebasestorage.app',
    iosBundleId: 'com.piyuo.counter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05_2KKCP6tc0Q_E3yHbPklUw1Dlm8dyE',
    appId: '1:339726104003:ios:29bd9a2427a0cbdbe37976',
    messagingSenderId: '339726104003',
    projectId: 'counter-964dc',
    storageBucket: 'counter-964dc.firebasestorage.app',
    iosBundleId: 'com.piyuo.counter',
  );
}
