# ios/fastlane/Fastfile

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the Apple App Store(ios)"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"]
    )

    # Fetch the latest build number from App Store Connect
    # This ensures we always increment from the highest number Apple knows about
    current_app_store_build_number = app_store_build_number()

    # Increment the build number based on the fetched value
    # We add 1 to the highest build number found on App Store Connect
    new_build_number = (current_app_store_build_number.to_i + 1).to_s
    increment_build_number(
      xcodeproj: "Counter.xcodeproj",
      build_number: new_build_number
    )

    # Build the app with the newly incremented build number
    build_app(workspace: "Counter.xcworkspace", scheme: "Runner",export_method: "app-store")

    # Upload the app to App Store Connect
    upload_to_app_store(
      precheck_include_in_app_purchases: false
    )
  end
end
