// TOC:
//  - OnboardingRouteData: /onboarding
//  - Onboarding1RouteData: 1
//  - Onboarding2RouteData: 2
//  - SystemRouteData: system nested under onboarding2
//  - CTARouteData: /cta (root level, breaks back stack)
//  - InvitationRouteData: invitation nested under cta (optional token query param)
//  - InvitationSuccessRouteData: invitation success ($extra: Invitation)
//  - PiyuoRouteData: piyuo nested under cta
//  - PiyuoSubscriptionRouteData: subscription nested under piyuo
//  - ServerRouteData: server nested under cta
//  - ServerSuccessRouteData: server success (url query param)
//  - ServerSubscriptionRouteData: subscription nested under server
//  - DemoRouteData: demo nested under cta
//
// Architecture note:
//  - Each class uses the `with $ClassName` mixin (generated by go_router_builder).
//  - Query params are declared as nullable fields; path params go in the route path template.
//  - $extra is used for non-serialisable objects (Invitation); the navigation event bus
//    passes it via router.push/go(path, extra: value) — it is NOT part of the URL.

import 'package:core_domain/core_domain.dart' as core_domain;
import 'package:core_domain/core_domain.dart' show Invitation; // required by go_router_builder generated code
import 'package:feature_onboarding/screens/camera_test_screen.dart';
import 'package:feature_onboarding/screens/cta_screen.dart';
import 'package:feature_onboarding/screens/invitation_screen.dart';
import 'package:feature_onboarding/screens/invitation_success_screen.dart';
import 'package:feature_onboarding/screens/local_screen.dart';
import 'package:feature_onboarding/screens/onboarding1_screen.dart';
import 'package:feature_onboarding/screens/onboarding2_screen.dart';
import 'package:feature_onboarding/screens/onboarding_screen.dart';
import 'package:feature_onboarding/screens/personal_custom_screen.dart';
import 'package:feature_onboarding/screens/personal_custom_success_screen.dart';
import 'package:feature_onboarding/screens/personal_piyuo_screen.dart';
import 'package:feature_onboarding/screens/subscription_screen.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'onboarding_route_data.g.dart';

@TypedGoRoute<OnboardingRouteData>(
  path: '/onboarding',
  routes: [
    TypedGoRoute<OnboardingIntroPrivacyRouteData>(
      path: 'intro_privacy',
      routes: [
        TypedGoRoute<OnboardingIntroCollectRouteData>(
          path: 'intro_collect',
          routes: [TypedGoRoute<CameraTestRouteData>(path: 'camera_test')],
        ),
      ],
    ),
  ],
)
class OnboardingRouteData extends GoRouteData with $OnboardingRouteData {
  const OnboardingRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => OnboardingScreen();
}

class OnboardingIntroPrivacyRouteData extends GoRouteData with $OnboardingIntroPrivacyRouteData {
  const OnboardingIntroPrivacyRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => Onboarding1Screen();
}

class OnboardingIntroCollectRouteData extends GoRouteData with $OnboardingIntroCollectRouteData {
  const OnboardingIntroCollectRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => Onboarding2Screen();
}

class CameraTestRouteData extends GoRouteData with $CameraTestRouteData {
  const CameraTestRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const CameraTestScreen();
}

@TypedGoRoute<CTARouteData>(
  path: '/cta',
  routes: [
    TypedGoRoute<SubscriptionRouteData>(path: 'cta_subscription'),
    TypedGoRoute<InvitationRouteData>(
      path: 'cta_invitation',
      routes: [TypedGoRoute<InvitationSuccessRouteData>(path: 'cta_invitation_success')],
    ),
    TypedGoRoute<PersonalPiyuoRouteData>(
      path: 'cta_personal_piyuo',
      routes: [TypedGoRoute<PersonalPiyuoSuccessRouteData>(path: 'cta_personal_piyuo_success')],
    ),
    TypedGoRoute<PersonalCustomRouteData>(
      path: 'cta_personal_custom',
      routes: [TypedGoRoute<PersonalCustomSuccessRouteData>(path: 'cta_personal_custom_success')],
    ),
    TypedGoRoute<LocalOnlyRouteData>(path: 'cta_local_only'),
  ],
)
class CTARouteData extends GoRouteData with $CTARouteData {
  const CTARouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const CTAScreen();
}

class InvitationRouteData extends GoRouteData with $InvitationRouteData {
  const InvitationRouteData({this.token});

  /// Optional deep-link token appended as a query parameter.
  final String? token;

  @override
  Widget build(BuildContext context, GoRouterState state) => const InvitationScreen();
}

class InvitationSuccessRouteData extends GoRouteData with $InvitationSuccessRouteData {
  const InvitationSuccessRouteData({this.$extra});

  /// The validated invitation — passed via router.push extra, never serialize to the URL.
  final core_domain.Invitation? $extra;

  @override
  Widget build(BuildContext context, GoRouterState state) => InvitationSuccessScreen(invitation: $extra!);
}

class PersonalPiyuoRouteData extends GoRouteData with $PersonalPiyuoRouteData {
  const PersonalPiyuoRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const PersonalPiyuoScreen();
}

class PersonalPiyuoSuccessRouteData extends GoRouteData with $PersonalPiyuoSuccessRouteData {
  const PersonalPiyuoSuccessRouteData({required this.url});

  /// The server URL appended as a query parameter.
  final String url;

  @override
  Widget build(BuildContext context, GoRouterState state) => PersonalCustomSuccessScreen(url: url);
}

class PersonalCustomRouteData extends GoRouteData with $PersonalCustomRouteData {
  const PersonalCustomRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const PersonalCustomScreen();
}

class PersonalCustomSuccessRouteData extends GoRouteData with $PersonalCustomSuccessRouteData {
  const PersonalCustomSuccessRouteData({required this.url});

  /// The server URL appended as a query parameter.
  final String url;

  @override
  Widget build(BuildContext context, GoRouterState state) => PersonalCustomSuccessScreen(url: url);
}

class SubscriptionRouteData extends GoRouteData with $SubscriptionRouteData {
  const SubscriptionRouteData({required this.nextPage});

  final String nextPage;

  @override
  Widget build(BuildContext context, GoRouterState state) => SubscriptionScreen(nextPage: nextPage);
}

class LocalOnlyRouteData extends GoRouteData with $LocalOnlyRouteData {
  const LocalOnlyRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const LocalScreen();
}
