// TOC:
//  - OnboardingRouteData: /onboarding
//  - Onboarding1RouteData: 1
//  - Onboarding2RouteData: 2
//  - SystemRouteData: system nested under onboarding2
//  - CTARouteData: /cta (root level, breaks back stack)
//  - InvitationRouteData: invitation nested under cta (optional token query param)
//  - InvitationSuccessRouteData: invitation success ($extra: Invitation)
//  - PiyuoRouteData: piyuo nested under cta
//  - PiyuoSubscriptionRouteData: subscription nested under piyuo
//  - ServerRouteData: server nested under cta
//  - ServerSuccessRouteData: server success (url query param)
//  - ServerSubscriptionRouteData: subscription nested under server
//  - DemoRouteData: demo nested under cta
//
// Architecture note:
//  - Each class uses the `with $ClassName` mixin (generated by go_router_builder).
//  - Query params are declared as nullable fields; path params go in the route path template.
//  - $extra is used for non-serialisable objects (Invitation); the navigation event bus
//    passes it via router.push/go(path, extra: value) — it is NOT part of the URL.

import 'package:core_domain/core_domain.dart' as core_domain;
import 'package:core_domain/core_domain.dart' show Invitation; // required by go_router_builder generated code
import 'package:feature_onboarding/screens/cta_screen.dart';
import 'package:feature_onboarding/screens/invitation_screen.dart';
import 'package:feature_onboarding/screens/invitation_success_screen.dart';
import 'package:feature_onboarding/screens/local_screen.dart';
import 'package:feature_onboarding/screens/onboarding1_screen.dart';
import 'package:feature_onboarding/screens/onboarding2_screen.dart';
import 'package:feature_onboarding/screens/onboarding_screen.dart';
import 'package:feature_onboarding/screens/personal_custom_screen.dart';
import 'package:feature_onboarding/screens/personal_custom_success_screen.dart';
import 'package:feature_onboarding/screens/personal_piyuo_screen.dart';
import 'package:feature_onboarding/screens/subscription_screen.dart';
import 'package:feature_onboarding/screens/system_screen.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'onboarding_route_data.g.dart';

@TypedGoRoute<OnboardingRouteData>(
  path: '/onboarding',
  routes: [
    TypedGoRoute<Onboarding1RouteData>(
      path: '1',
      routes: [
        TypedGoRoute<Onboarding2RouteData>(
          path: '2',
          routes: [TypedGoRoute<SystemRouteData>(path: 'system')],
        ),
      ],
    ),
  ],
)
class OnboardingRouteData extends GoRouteData with $OnboardingRouteData {
  const OnboardingRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => OnboardingScreen();
}

class Onboarding1RouteData extends GoRouteData with $Onboarding1RouteData {
  const Onboarding1RouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => Onboarding1Screen();
}

class Onboarding2RouteData extends GoRouteData with $Onboarding2RouteData {
  const Onboarding2RouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => Onboarding2Screen();
}

class SystemRouteData extends GoRouteData with $SystemRouteData {
  const SystemRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const SystemScreen();
}

@TypedGoRoute<CTARouteData>(
  path: '/cta',
  routes: [
    TypedGoRoute<PiyuoSubscriptionRouteData>(path: 'piyuo-subscription'),
    TypedGoRoute<ServerSubscriptionRouteData>(path: 'server-subscription'),
    TypedGoRoute<InvitationRouteData>(
      path: 'invitation',
      routes: [TypedGoRoute<InvitationSuccessRouteData>(path: 'success')],
    ),
    TypedGoRoute<PiyuoRouteData>(path: 'piyuo'),
    TypedGoRoute<ServerRouteData>(
      path: 'server',
      routes: [TypedGoRoute<ServerSuccessRouteData>(path: 'success')],
    ),
    TypedGoRoute<DemoRouteData>(path: 'demo'),
  ],
)
class CTARouteData extends GoRouteData with $CTARouteData {
  const CTARouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const CTAScreen();
}

class InvitationRouteData extends GoRouteData with $InvitationRouteData {
  const InvitationRouteData({this.token});

  /// Optional deep-link token appended as a query parameter.
  final String? token;

  @override
  Widget build(BuildContext context, GoRouterState state) => const InvitationScreen();
}

class InvitationSuccessRouteData extends GoRouteData with $InvitationSuccessRouteData {
  const InvitationSuccessRouteData({this.$extra});

  /// The validated invitation — passed via router.push extra, never serialize to the URL.
  final core_domain.Invitation? $extra;

  @override
  Widget build(BuildContext context, GoRouterState state) => InvitationSuccessScreen(invitation: $extra!);
}

class PiyuoRouteData extends GoRouteData with $PiyuoRouteData {
  const PiyuoRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const PersonalPiyuoScreen();
}

class ServerRouteData extends GoRouteData with $ServerRouteData {
  const ServerRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const PersonalCustomScreen();
}

class ServerSuccessRouteData extends GoRouteData with $ServerSuccessRouteData {
  const ServerSuccessRouteData({required this.url});

  /// The server URL appended as a query parameter.
  final String url;

  @override
  Widget build(BuildContext context, GoRouterState state) => PersonalCustomSuccessScreen(url: url);
}

class PiyuoSubscriptionRouteData extends GoRouteData with $PiyuoSubscriptionRouteData {
  const PiyuoSubscriptionRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const SubscriptionScreen(nextPage: 'piyuo');
}

class ServerSubscriptionRouteData extends GoRouteData with $ServerSubscriptionRouteData {
  const ServerSubscriptionRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const SubscriptionScreen(nextPage: 'server');
}

class DemoRouteData extends GoRouteData with $DemoRouteData {
  const DemoRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const LocalScreen();
}
