// TOC:
//  - OnboardingRouteData: /onboarding
//  - CTARouteData: cta (call to action)
//  - InvitationRouteData: invitation (optional token query param)
//  - InvitationSummaryRouteData: invitation-summary ($extra: Invitation)
//  - PiyuoRouteData: piyuo
//  - ServerRouteData: server
//  - ServerSummaryRouteData: summary (url query param)
//  - DemoRouteData: demo
//  - SubscriptionRouteData: subscription
//
// Architecture note:
//  - Each class uses the `with $ClassName` mixin (generated by go_router_builder).
//  - Query params are declared as nullable fields; path params go in the route path template.
//  - $extra is used for non-serialisable objects (Invitation); the navigation event bus
//    passes it via router.push/go(path, extra: value) — it is NOT part of the URL.

import 'package:core_domain/core_domain.dart' as core_domain;
import 'package:core_domain/core_domain.dart' show Invitation; // required by go_router_builder generated code
import 'package:feature_onboarding/screens/cta_screen.dart';
import 'package:feature_onboarding/screens/demo_screen.dart';
import 'package:feature_onboarding/screens/invitation_screen.dart';
import 'package:feature_onboarding/screens/invitation_summary_screen.dart';
import 'package:feature_onboarding/screens/onboarding_screen.dart';
import 'package:feature_onboarding/screens/piyuo_screen.dart';
import 'package:feature_onboarding/screens/server_screen.dart';
import 'package:feature_onboarding/screens/server_summary_screen.dart';
import 'package:feature_onboarding/screens/subscription_screen.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'onboarding_route_data.g.dart';

@TypedGoRoute<OnboardingRouteData>(
  path: '/onboarding',
  routes: [
    TypedGoRoute<CTARouteData>(path: 'cta'),
    TypedGoRoute<InvitationRouteData>(
      path: 'invitation',
      routes: [TypedGoRoute<InvitationSummaryRouteData>(path: 'summary')],
    ),
    TypedGoRoute<PiyuoRouteData>(path: 'piyuo'),
    TypedGoRoute<ServerRouteData>(
      path: 'server',
      routes: [TypedGoRoute<ServerSummaryRouteData>(path: 'summary')],
    ),
    TypedGoRoute<DemoRouteData>(path: 'demo'),
    TypedGoRoute<SubscriptionRouteData>(path: 'subscription'),
  ],
)
class OnboardingRouteData extends GoRouteData with $OnboardingRouteData {
  const OnboardingRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const OnboardingScreen();
}

class CTARouteData extends GoRouteData with $CTARouteData {
  const CTARouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const CTAScreen();
}

class InvitationRouteData extends GoRouteData with $InvitationRouteData {
  const InvitationRouteData({this.token});

  /// Optional deep-link token appended as a query parameter.
  final String? token;

  @override
  Widget build(BuildContext context, GoRouterState state) => const InvitationScreen();
}

class InvitationSummaryRouteData extends GoRouteData with $InvitationSummaryRouteData {
  const InvitationSummaryRouteData({this.$extra});

  /// The validated invitation — passed via router.push extra, never serialised to the URL.
  final core_domain.Invitation? $extra;

  @override
  Widget build(BuildContext context, GoRouterState state) => InvitationSummaryScreen(invitation: $extra!);
}

class PiyuoRouteData extends GoRouteData with $PiyuoRouteData {
  const PiyuoRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const PiyuoScreen();
}

class ServerRouteData extends GoRouteData with $ServerRouteData {
  const ServerRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const ServerScreen();
}

class ServerSummaryRouteData extends GoRouteData with $ServerSummaryRouteData {
  const ServerSummaryRouteData({required this.url});

  /// The server URL appended as a query parameter.
  final String url;

  @override
  Widget build(BuildContext context, GoRouterState state) => ServerSummaryScreen(url: url);
}

class DemoRouteData extends GoRouteData with $DemoRouteData {
  const DemoRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const DemoScreen();
}

class SubscriptionRouteData extends GoRouteData with $SubscriptionRouteData {
  const SubscriptionRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const SubscriptionScreen();
}
