name: core_runtime
description: "runtime implementation for counter domain"
version: 1.5.1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  shared_l10n: any
  core_domain: any
  flutter:
    sdk: flutter
  flutter_appkit:
    git:
      url: https://github.com/piyuo/flutter-appkit.git
      ref: v3.8.1
  flutter_vision:
    path: ../../../flutter-vision
  camera: ^0.12.0+2
  camera_macos: ^0.1.0
  camera_windows: ^0.2.6+4
  json_annotation: ^4.12.0
  flutter_riverpod: ^3.4.2 # block by analyzer
  riverpod_annotation: ^4.0.6 # block by analyzer
  universal_platform: ^1.1.0
  shared_preferences: ^2.5.5
  cryptography: ^2.9.0
  freezed_annotation: ^3.1.0
  app_links: ^7.2.1
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  http: ^1.6.0
  uuid: ^4.6.0
  path: ^1.9.1
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.8.1
  flutter_lints: ^6.0.0
  analyzer: ^13.3.0
  riverpod_generator: ^4.0.8 # block by analyzer
  freezed: ^4.0.1
  drift_dev: ^2.33.0
  json_serializable: ^6.14.1
  build_runner: ^2.16.0
  json_schema: ^5.1.5
  shared_preferences_platform_interface: ^2.4.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
