name: core_runtime
description: "runtime implementation for counter domain"
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  shared_l10n: any
  core_domain: any
  flutter:
    sdk: flutter
  flutter_appkit:
    git:
      url: https://github.com/piyuo/flutter-appkit.git
      ref: v3.2.0
  flutter_vision:
    path: ../../../flutter-vision
  camera: ^0.11.3+1
  camera_macos: ^0.0.9
  camera_windows: ^0.2.6+4
  json_annotation: ^4.10.0
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  universal_platform: ^1.1.0
  shared_preferences: ^2.5.4
  freezed_annotation: ^3.1.0
  app_links: ^6.4.0
  flutter_secure_storage: ^9.2.4
  drift: ^2.26.0
  drift_flutter: ^0.2.0
  http: ^1.1.0
  uuid: ^4.3.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.3
  flutter_lints: ^6.0.0
  analyzer: ^9.0.0
  riverpod_generator: ^4.0.3
  freezed: ^3.2.5
  drift_dev: ^2.26.0
  json_serializable: ^6.12.0
  build_runner: ^2.11.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
