# android/fastlane/Fastfile
default_platform(:android)

platform :android do
  desc "Release a new version to the Google Play Store"
  lane :release do
    gradle(task: "clean bundleRelease") # or assembleRelease if not using .aab
    upload_to_play_store(track: "internal")
  end
end
