name: feature_monitor
description: "The monitor to preview video."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.11.4
  core_domain: ^0.0.1
  flutter:
    sdk: flutter
  flutter_vision:
    path: ../../../flutter-vision
  flutter_appkit:
    git:
      url: https://github.com/piyuo/flutter-appkit.git
      ref: v3.1.1
  flutter_riverpod: ^3.3.1
  go_router: ^17.1.0
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
#flutter:
