# .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - main # our main branch
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      issues: write # This is important for label creation
      contents: write # This is crucial for creating branches and committing changes
      pull-requests: write # This is crucial for creating and updating PRs
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          # Automatically detects release-please-config.json
          # and .release-please-manifest.json in the root directory
          target-branch: main